# Generated by Django 4.1.5 on 2023-01-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArea', models.CharField(max_length=80, unique=True)),
                ('descripcionArea', models.CharField(max_length=250)),
            ],
        ),
    ]
