# Generated by Django 4.1.5 on 2023-01-27 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpleado', models.CharField(max_length=150)),
                ('apellidoEmpleado', models.CharField(max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='empleado')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.cargo')),
            ],
        ),
    ]
